### ISSUE TITLE
Need to define _NO_CRT_STDIO_INLINE to use printf, etc

### ISSUE THREAD

**Issue by azlan** [neosmart/msvcrt.lib#1]
If not defined, we will get these errors.
1>main.obj : error LNK2001: unresolved external symbol ___acrt_iob_func
1>main.obj : error LNK2001: unresolved external symbol ___stdio_common_vfprintf
1>main.obj : error LNK2001: unresolved external symbol ___stdio_common_vfscanf

**Comment by mqudsi** [comment]
I'm not sure if there's anything this project can do about that? This project simply exposes the .lib files needed to link against `msvcrt.dll`, but you still need to configure your IDE to not use its own version of functions.
